//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TILAHA.Controllers.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehouseDBEntities : DbContext
    {
        public WarehouseDBEntities()
            : base("name=WarehouseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Henkilot> Henkilot { get; set; }
        public virtual DbSet<Laitteet> Laitteet { get; set; }
        public virtual DbSet<Huolto> Huolto { get; set; }
        public virtual DbSet<Kuva> Kuva { get; set; }
        public virtual DbSet<Lainaaja> Lainaaja { get; set; }
        public virtual DbSet<Laite> Laite { get; set; }
        public virtual DbSet<Osoite> Osoite { get; set; }
        public virtual DbSet<Sijainti> Sijainti { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Takuu> Takuu { get; set; }
        public virtual DbSet<Varuste> Varuste { get; set; }
    }
}
