//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TILAHA.Controllers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Huolto
    {
        public int DeviceId { get; set; }
        public string Service { get; set; }
        public Nullable<long> ServicePhone { get; set; }
        public string Servicewww { get; set; }
        public string ServiceMail { get; set; }
    }
}
