//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TILAHA.Controllers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kuva
    {
        public int DeviceID { get; set; }
        public byte[] Image { get; set; }
        public byte[] Image2 { get; set; }
        public byte[] Image3 { get; set; }
    }
}
