//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TILAHA.Controllers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laitteet
    {
        public int DeviceId { get; set; }
        public int WarrantyId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string SN { get; set; }
        public string Condition { get; set; }
        public string DeviceType { get; set; }
        public string AddInfo { get; set; }
        public Nullable<System.DateTime> PurcDate { get; set; }
        public Nullable<System.DateTime> WarrEndDate { get; set; }
        public int PurchPrize { get; set; }
    }
}
