//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TILAHA.Controllers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laite
    {
        public int DeviceId { get; set; }
        public long AccId { get; set; }
        public string Model { get; set; }
        public string Type { get; set; }
        public string SN { get; set; }
        public string Cond { get; set; }
        public string DeviceType { get; set; }
        public string AddInfo { get; set; }
        public System.DateTime PurcDate { get; set; }
        public Nullable<System.DateTime> WarrEndDate { get; set; }
        public Nullable<short> PurchPrize { get; set; }
    }
}
