//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TILAHA.Controllers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sijainti
    {
        public int DeviceId { get; set; }
        public string Building { get; set; }
        public string Space { get; set; }
        public string Locker { get; set; }
        public string Shelf { get; set; }
        public string Status { get; set; }
    }
}
