//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TILAHA.Controllers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Varuste
    {
        public int AccId { get; set; }
        public int DeviceID { get; set; }
        public string Acc1 { get; set; }
        public string Acc2 { get; set; }
        public string Acc3 { get; set; }
        public string Acc4 { get; set; }
    }
}
